data<-read.csv("dmf.csv")
summary(data)
hist(data$dmf)
hist(data$flor)

mod1<-lm(dmf~flor,data)
print(mod1)
summary(mod1)
sum((data$dmf-mod1$fitted.values)^2)
rmse(data$dmf,mod1$fitted.values)
plot(density(mod1$residuals))
scatter.smooth(x=mod1$residuals, y=mod1$fitted.values, main="error ~ predicted")
scatter.smooth(x=data$dmf, y=mod1$fitted.values, main="predicted ~ response")

mod2<-lm(dmf~flor+flor*flor,data)
print(mod2)
summary(mod2)
sum((data$dmf- mod2$fitted.values)^2)
rmse(data$dmf,mod2$fitted.values)
plot(density(mod2$residuals))
scatter.smooth(x=mod2$residuals, y=mod2$fitted.values, main="error ~ predicted")
scatter.smooth(x=data$dmf, y=mod2$fitted.values, main="predicted ~ response")

mod3<-lm(dmf~flor+flor*flor+sqrt(flor),data)
print(mod3)
summary(mod3)
sum((data$dmf- mod3$fitted.values)^2)
rmse(data$dmf,mod3$fitted.values)
plot(density(mod3$residuals))
scatter.smooth(x=mod3$residuals, y=mod3$fitted.values, main="error ~ predicted")
scatter.smooth(x=data$dmf, y=mod3$fitted.values, main="predicted ~ response")


fourootflor <- sqrt(sqrt(data$flor))
mod4<-lm(dmf ~log(data$flor+1)+ data$flor + (data$flor*data$flor+1)/sqrt(data$flor) + 1/fourootflor,data)
print(mod4)
summary(mod4)
sum((data$dmf- mod4$fitted.values)^2)
rmse(data$dmf,mod4$fitted.values)
plot(density(mod4$residuals))
scatter.smooth(x=mod4$residuals, y=mod4$fitted.values, main="error ~ predicted")
scatter.smooth(x=data$dmf, y=mod4$fitted.values, main="predicted ~ response")
